### ISSUE TITLE
-damage command not found

### ISSUE THREAD

**Issue by EisenRa** [grenaud/gargammel#1]
Firstly, thank you for writing this awesome software!

I've found a small bug in gargammel.pl: calling -damage results in an "Unknown option" error. However, calling -briggs does the job. 

Cheers,
Raphael

**Comment by grenaud** [comment]
Dear Raphael,
Thank you for the laudatory words and notifying me of this bug. I have since fixed the perl code. Let me know this is ok and if you have any other bug reports or feature requests :-)

Gabriel

**Comment by EisenRa** [comment]
Dear Gabriel,

It's working fine now.

Thanks!
Raphael
