### ISSUE TITLE
'ms2chromosomes.py' can't find 'ms' program 

### ISSUE THREAD

**Issue by baif666** [grenaud/gargammel#13]
Hi, 

I install gargammel using conda as you suggested (`conda env create -f environment.yml`) but after I activated the environment 'ms2chromosomes.py' can't find 'ms' program :
```
$ python ../ms2chromosomes.py  -s 0.2 -f . -n 1000
Detecting program: ms
Cannot find program: ms please make sure it is installed
```

But if I run 'type ms', it gives the right result : 
```
$ type ms
ms is /home/xxxxx/anaconda3/envs/gargammel/bin/ms
```

What's the problem?

**Comment by baif666** [comment]
The problem is `/bin/bash -i -c 'type ms'` can't find the right path of 'ms' program.

```
$ /bin/bash -i -c 'type ms'
bash: type: ms: not found
```

But `which ms` work well. Could we modify the code of `which()` function to use `which` command?

**Comment by grenaud** [comment]
you use conda? could you put it as hard path in the script?

**Comment by baif666** [comment]
Yes, hard path also works

**Comment by baif666** [comment]
Do we need to change it or just use the hard path? I will submit a pull request to modify it later.

**Comment by grenaud** [comment]
I would just hardcode it in the perl script and remove the error detection.

**Comment by baif666** [comment]
ok thanks!
