### ISSUE TITLE
Can I use human reference genome in the 'endo' folder?

### ISSUE THREAD

**Issue by baif666** [grenaud/gargammel#14]
Hi, 

In the tutorial, you use 'ms' to stimulate human fragments. Can I directly use the human reference genome or other modern human data in the 'endo' folder? If I don't care about the difference between ancient and present-day humans.

**Comment by grenaud** [comment]
yes absolutely! endo/ just means endogenous. Whatever genome you put in there will be used as endogenous. Do you care about het. sites? If so, you need 2 fasta files, 1 for each chromosome. Otherwise, it will assume the human genome is haploid.

**Comment by baif666** [comment]
If I don't care about the het. site,  can I put only one genome? But I found in this way, it takes more time to create aDNA fragments.

**Comment by baif666** [comment]
Thanks!

**Comment by grenaud** [comment]
Yes absolutely, if you just put one genome, it will interpret that genome is haploid. If you do not care about heterozygous sites, this is fine :-)
