### ISSUE TITLE
Does gargammel support fragmentation based on the base preceeding the break?

### ISSUE THREAD

**Issue by computations** [grenaud/gargammel#16]
I was wondering if this software supports preferentially starting fragments based on the preceding base. For example, the plots in https://doi.org/10.1073/pnas.0704665104 suggest that as DNA ages, it breaks preferentially on some bases rather than others. I would like to see if this particular breaking pattern has effects on downstream analysis.

**Comment by grenaud** [comment]
By yes it can do that, you need to give it a profile where you give it probabilities of breaks when it will generate fragments according to that.  

By the way this does not seem like a bug more like a question :-) could you post this on biostars instead and email me and I will answer. Their way that increases visibility for this question
