### ISSUE TITLE
fixed seed and add an annotation in the simulated read header

### ISSUE THREAD

**Issue by chenjie2022** [grenaud/gargammel#17]
Hi Gabriel,

Currently gargammel simulates datasets by randomly extracting reads from a genome. Would it be possible to (1) add an option to take fixed seed as input, so that for a genome we can generate different simulated datasets with different damage degrees (both for fragSim or deamSim), while for each of these generated datasets we have every read coming from exactly the same position on the reference genome? In other word, we can simulate different damage degrees on the same reads; and (2) add an annotation in the simulated read header to indicate that a (or mutiple) C>G or A>T damage was added?

**Comment by grenaud** [comment]
Hello! I have added the seed in fragSim, seems to work, I will add it in deamSim tomorrow :-)

**Comment by grenaud** [comment]
Hello! I have now added the seed to deamSim. 
For the type, it is relatively to infer, use the -name option and if you see a positive number ex: _DEAM:5 then it was a C to T, _DEAM:-5 was a G to A?

Let me know if you have any further requests :-)
