### ISSUE TITLE
Sequencing system options

### ISSUE THREAD

**Issue by mmaitenat** [grenaud/gargammel#3]
Hi! I've been using gargammel for a while and I think I encountered some issue with the available options for the sequencing system to be used to simulate the reads. When I look at the help of gargammel through `./gargammel.pl -h`, I get the following as to the -ss option: 

-ss     [system]                	Illumina platfrom to use, the parentheses indicate the max. read length
	                                	use the shorthand in the left column:
                                                                        (single-end, paired-end)
						   GA2  - GenomeAnalyzer II (  50bp,  75bp)
						   HS20 - HiSeq 2000        ( 100bp,   N/A)
						   HS25 - HiSeq 2500        ( 125bp, 150bp) (Default)
						   HSXt - HiSeqX TruSeq     ( 150bp,   N/A)
						   MSv1 - MiSeq v1          ( 250bp,   N/A)
						   MSv3 - MiSeq v3          ( 250bp,   N/A)

According to this, only GA2 and HS25 can be used with paired-end reads. 
However, and correct me if I am wrong, when I check ART, which is the program used for creating the reads, I saw that the six of them can be used with paired-end reads. I also noticed that those length values between parentheses just correspond to lengths for which error profiles have been created.

Could you tell if I am missing something or this is actually some mistake here?
Many thanks!!

**Comment by grenaud** [comment]
Dear mmaitenat, thank you for submitting this, you are 100% right. Is seems that ART just writes 1 number if the read length for single and paired-end mode are the same. This is confusion but I changed it to:

`                                                                        (single-end, paired-end)`
						 `  GA2  - GenomeAnalyzer II (  50bp,  75bp)`
						`   HS20 - HiSeq 2000        ( 100bp, 100bp)`
						`   HS25 - HiSeq 2500        ( 125bp, 150bp) (Default)`
						`   HSXt - HiSeqX TruSeq     ( 150bp, 150bp)`
						`   MSv1 - MiSeq v1          ( 250bp, 250bp)`
					`	   MSv3 - MiSeq v3          ( 250bp, 250bp)`

I this corrects the read length problem, let me know if I can close the issue.

**Comment by mmaitenat** [comment]
Great! I checked the new version of gargammel.pl and now is working fine! The issue is solved to me. Many thanks!!

**Comment by grenaud** [comment]
Thank you for reporting this!
